/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RsDivider */

#ifndef _Included_RsDivider
#define _Included_RsDivider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RsDivider
 * Method:    divNumbers
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_RsDivider_divNumbers
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
